#ifndef ERROR_CODES_H
#define ERROR_CODES_H

// Codigos de error del sistema
typedef enum {
	ERROR_NONE = 0,
	ERROR_LIMIT_SWITCH,
	ERROR_TIMEOUT,
	ERROR_INVALID_COMMAND,
	ERROR_OUT_OF_BOUNDS,
	ERROR_ENCODER_MISMATCH,
	ERROR_COMMUNICATION,
	ERROR_EMERGENCY_STOP,
	ERROR_MOTOR_STALL,
	ERROR_INVALID_PARAMETER
} error_code_t;

// Mensajes de error para enviar
#define ERROR_MSG_LIMIT     "ERR:LIMIT"
#define ERROR_MSG_TIMEOUT   "ERR:TIMEOUT"
#define ERROR_MSG_BOUNDS    "ERR:BOUNDS"
#define ERROR_MSG_COMMAND   "ERR:CMD"
#define ERROR_MSG_ESTOP     "ERR:ESTOP"

#endif